### ISSUE TITLE
I can't build with 4.11 with Assembly error CS0246

### ISSUE THREAD

**Issue by OmeGaCinoS** [thirdweb-dev/unity-sdk#182]
I try to build in HTML5 and get this : 
![image](https://github.com/thirdweb-dev/unity-sdk/assets/5391554/90e452a5-d3ed-4c3b-ad81-0e5b4cbf4115)

Assets\Thirdweb\Core\Scripts\WalletsUI\InAppWalletUI.cs(15,7): error CS0246: The type or namespace name 'Codice' could not be found (are you missing a using directive or an assembly reference?)

I try to resolve it, but... I got no error in the script and I'm not able to find this "Codice" library

**Comment by 0xFirekeeper** [comment]
Hey @OmeGaCinoS we don't use Codice, open that script and check if there's an added reference to it in you project, and if so feel free to remove it. Checking 4.11 we didn't have a reference then either.
